# Generated by Django 4.0.5 on 2022-07-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aFirebaseOperator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=16)),
                ('pid', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=16)),
                ('number', models.IntegerField(max_length=99)),
                ('position', models.CharField(max_length=2)),
            ],
        ),
    ]
