# Generated by Django 4.0.5 on 2022-07-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aFirebaseOperator', '0002_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(),
        ),
    ]
