# Generated by Django 4.0.5 on 2022-07-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aFirebaseOperator', '0003_alter_player_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=32)),
                ('section', models.IntegerField(max_length=34)),
                ('hometeam', models.CharField(max_length=4)),
                ('homescore', models.IntegerField()),
                ('awayteam', models.CharField(max_length=4)),
                ('awayscore', models.IntegerField()),
                ('kickoff', models.DateField()),
                ('stadium', models.CharField(max_length=32)),
            ],
        ),
    ]
