# Generated by Django 4.0.5 on 2022-07-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aFirebaseOperator', '0003_alter_player_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=32)),
                ('team', models.CharField(max_length=8)),
                ('opponent', models.CharField(max_length=8)),
                ('kickoff', models.DateField()),
            ],
        ),
    ]
