# Generated by Django 4.0.5 on 2022-07-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aFirebaseOperator', '0004_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='section',
            field=models.IntegerField(),
        ),
    ]
