# Generated by Django 4.0.5 on 2022-07-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aFirebaseOperator', '0004_match'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
