# Generated by Django 4.0.5 on 2022-09-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aFirebaseOperator', '0005_delete_comment_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='point',
            field=models.FloatField(default=0),
        ),
    ]
