# Generated by Django 4.1.5 on 2023-01-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aFirebaseOperator', '0006_player_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='com',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='player',
            name='sdev',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='player',
            name='var',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='player',
            name='point',
            field=models.FloatField(default=-1),
        ),
    ]
