# Generated by Django 4.0.5 on 2022-09-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aFirebaseOperator', '0006_player_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='point',
            field=models.FloatField(default=-1),
        ),
    ]
